import './utility-menu.css';
export function createDestinationMenu({areas,travel,stop=()=>{},blocked=()=>false}){
 const visited=new Set(),dialog=document.createElement('dialog');dialog.id='destination-menu';dialog.className='utility-menu';dialog.setAttribute('aria-label','Where to?');
 dialog.innerHTML='<div class="utility-heading"><h2>Where to?</h2><button data-close aria-label="Close destinations">×</button></div><p>Choose your next adventure.</p><div class="utility-options"></div><p class="utility-status" role="status"></p><button data-travel>Travel</button>';document.body.append(dialog);
 let source=null,selected=null,callback=null;
 const close=()=>{dialog.close();source=null;callback=null;};dialog.querySelector('[data-close]').onclick=close;dialog.addEventListener('cancel',()=>{source=null;callback=null;});
 function render(){const list=dialog.querySelector('.utility-options');list.replaceChildren();for(const area of areas.list()){const button=document.createElement('button');button.disabled=area.id===areas.id;button.setAttribute('aria-pressed',String(selected===area.id));const name=document.createElement('strong'),detail=document.createElement('small');name.textContent=(area.name||area.id)+(area.id===areas.id?' · You are here':!visited.has(area.id)?' · New':'');detail.textContent=area.description||'';button.append(name,detail);button.onclick=()=>{selected=area.id;render();};list.append(button);}dialog.querySelector('[data-travel]').disabled=!source||!selected||selected===areas.id;}
 dialog.querySelector('[data-travel]').onclick=()=>{if(!source?.available()||blocked()){dialog.querySelector('[role=status]').textContent='The crystal is unavailable. Close and approach it again.';return;}const arrive=callback;if(travel.request(selected,{source,onArrive:()=>{visited.add(areas.id);arrive?.();}})){close();}else dialog.querySelector('[role=status]').textContent='There is no safe arrival space. Try again in a moment.';};
 return {open(actor,onArrive){if(blocked()||actor&&!actor.available())return false;stop();visited.add(areas.id);source=actor;callback=onArrive;selected=areas.active?.recommendedDestination||(actor?.destination!==areas.id?actor?.destination:null);selected=areas.get(selected)?selected:areas.list().find(a=>a.id!==areas.id)?.id;dialog.querySelector('[role=status]').textContent=actor?'':'Preview only — approach an Iter Crystal to travel.';render();dialog.showModal();return true;},close,update(){if(dialog.open&&source&&!source.available())close();},get isOpen(){return dialog.open;},reset(){close();visited.clear();}};
}
