import test from 'node:test';
import assert from 'node:assert/strict';
import {createStationCrafting} from './station-crafting.js';
import {createEquipment} from './equipment.js';
import {createCombatStyles} from './combat-styles.js';
import {createSupplyOffers} from './supply-offers.js';
import {withinAttackRange,lineOfSight,attackRoute} from './combat-range.js';
import {makeCinderholdTiles,CINDERHOLD,createTrainingProgress} from './cinderhold-rules.js';
import {makeWillowbankTiles} from './willowbank-rules.js';
import {findPath} from './world.js';
import {interactionRoute} from './interaction-route.js';
function stationFixture(){const inventory={copperOre:4,copperIngots:0,hammers:1};let available=true,reach=true,rewards=0;const station={kind:'furnace',available:()=>available};const system=createStationCrafting({inventory,stop:()=>system.cancel(),inReach:()=>reach,completed(){rewards++;}});return {inventory,system,station,get rewards(){return rewards;},set available(v){available=v;},set reach(v){reach=v;}};}
test('portable metalwork spends inputs once, retains hammer, grants Smithing and rejects wrong stations',()=>{const f=stationFixture();assert.equal(f.system.start('copperDagger',f.station),false);assert.ok(f.system.start('copperIngots',f.station));assert.equal(f.system.start('copperIngots',f.station),false);f.system.update(3);f.system.update(30);assert.equal(f.inventory.copperOre,3);assert.equal(f.inventory.copperIngots,1);assert.equal(f.rewards,1);assert.equal(f.system.skill.xp,20);f.station.kind='anvil';assert.ok(f.system.start('copperDagger',f.station));f.system.update(3);assert.equal(f.inventory.copperDagger,1);assert.equal(f.inventory.hammers,1);assert.equal(f.inventory.copperIngots,0);});
test('station interruption, missing tools, invalidated reach/source, and repeated restart preserve inputs',()=>{for(const interrupt of [f=>f.system.cancel(),f=>f.available=false,f=>f.reach=false]){const f=stationFixture();f.system.start('copperIngots',f.station);f.system.update(1);interrupt(f);f.system.update(10);assert.equal(f.inventory.copperOre,4);assert.equal(f.rewards,0);f.available=f.reach=true;assert.ok(f.system.start('copperIngots',f.station));f.system.update(3);assert.equal(f.rewards,1);}const f=stationFixture();f.station.kind='anvil';f.inventory.copperIngots=4;f.inventory.hammers=0;assert.equal(f.system.start('copperShield',f.station),false);});
test('slot conflicts preserve inventory, clear last copy, and distinguish variants',()=>{const inventory={bows:1,copperDagger:1,copperShield:1,swords:1};const e=createEquipment({inventory});e.toggle('copperDagger');e.toggle('copperShield');assert.equal(e.attack.power,10);assert.equal(e.shield.resistance,50);e.toggle('bows');assert.deepEqual([e.slots.right,e.slots.left],[null,'bows'],'the bow takes the off hand and frees the other');assert.equal(e.shield,null);assert.equal(e.attack.range,6);assert.equal(inventory.copperShield,1);e.toggle('copperShield');assert.equal(e.slots.main,null);e.toggle('swords');assert.equal(e.isEquipped('copperDagger'),false);inventory.swords=0;assert.equal(e.attack.style,'unarmed');});
test('spell learning/selection is portable, idempotent and blocked only by shared activity',()=>{const equipment=createEquipment({inventory:{}});let busy=false;const styles=createCombatStyles({equipment,busy:()=>busy});assert.equal(styles.select('energyStrike'),false);assert.ok(styles.learn('energyStrike'));assert.equal(styles.learn('energyStrike'),false);assert.ok(styles.select('energyStrike'));assert.equal(styles.attack.style,'magic');assert.equal(styles.attack.mana,4);busy=true;assert.equal(styles.select(null),false);assert.ok(styles.setStrategy('strong'),'strategy may change mid-combat');busy=false;styles.select(null);assert.equal(styles.attack.style,'unarmed');styles.reset();assert.deepEqual(styles.state,{selected:null,learned:[],strategy:'technical',abilities:[],quickSpell:null});});
test('supply offers refill only when eligible and never repeat a one-time starter grant',()=>{const inventory={};let changes=0;const supplies=createSupplyOffers({inventory,changed:()=>changes++});assert.ok(supplies.claim('archerKit'));assert.equal(supplies.claim('archerKit'),false);assert.equal(supplies.claim('arrows'),false);inventory.arrows=0;assert.ok(supplies.claim('arrows'));assert.equal(inventory.arrows,20);assert.ok(supplies.claim('meal'));assert.equal(supplies.claim('meal'),false);inventory.cookedFish=0;assert.ok(supplies.claim('meal'));assert.equal(changes,4);});
function grid(){return new Map(Array.from({length:49},(_,i)=>{const t={x:i%7,z:Math.floor(i/7),h:1,blocked:false};return [`${t.x},${t.z}`,t];}));}
test('ranged routes respect distance, solid sightlines, missing terrain and blocked corners',()=>{const world=grid(),from=world.get('1,3'),tile=world.get('5,3'),target={...tile,tile};tile.blocked=true;assert.ok(withinAttackRange(world,from,target,4));assert.equal(withinAttackRange(world,from,target,1),false);world.get('3,3').blocked=true;assert.equal(lineOfSight(world,from,target),false);const route=attackRoute(world,from,target,4);assert.ok(route?.route.length>0);assert.ok(withinAttackRange(world,route.at,target,4));world.delete('3,3');assert.equal(lineOfSight(world,from,target),false);world.get('2,3').blocked=true;assert.equal(lineOfSight(world,from,{x:2,z:4}),false);});
test('Cinderhold exceeds earlier reachable area and all landmarks have connected approach tiles',()=>{const tiles=makeCinderholdTiles(),world=new Map(tiles.map(t=>[`${t.x},${t.z}`,t])),start=world.get('7,28');const walkable=tiles.filter(t=>!t.blocked);assert.ok(walkable.length>=makeWillowbankTiles().filter(t=>!t.blocked).length*2);for(const t of walkable)assert.ok(findPath(world,start,t),`${t.x},${t.z}`);for(const [name,[x,z]] of Object.entries(CINDERHOLD)){const t=world.get(`${x},${z}`);assert.ok(!t.blocked,name);t.blocked=true;assert.ok(interactionRoute(world,start,{tile:t,x,z}),name);}assert.ok(Math.max(...tiles.map(t=>t.x))===40);});
test('tutorial observes early portable work, retains counts after consumption and optional lessons stay independent',()=>{const p=createTrainingProgress(),s=p.state;p.event('crafted','copperIngots');assert.equal(s.ingots,0);s.entered=true;for(let i=0;i<4;i++){p.event('resource',{copperOre:1});p.event('crafted','copperIngots');}p.event('crafted','copperDagger');p.event('crafted','copperShield');p.event('victory',{id:'proving',style:'unarmed'});s.phase='mine';p.advance(true);assert.equal(s.phase,'return');s.phase='bruiser';p.advance(true);assert.equal(s.phase,'graduate');s.phase='finished';s.ranged='target';p.event('victory',{id:'ranged-target',style:'magic'});assert.equal(s.ranged,'target');p.event('victory',{id:'ranged-target',style:'ranged'});p.event('victory',{id:'ranged-enemy',style:'ranged'});assert.equal(s.ranged,'done');assert.equal(s.magic,'offer');assert.equal(s.phase,'finished');p.reset();assert.equal(s.entered,false);});

test('batched terrain ray hits resolve the original logical tile across batch boundaries',async()=>{
 const {Group,Raycaster,Vector3}=await import('three');const {createTerrainBatch,terrainHitData}=await import('./terrain-batch.js');const {stoneTile}=await import('./training-models.js');
 const tiles=[{x:7,z:3,h:1},{x:8,z:3,h:1.5}],map=new Map(tiles.map(t=>[`${t.x},${t.z}`,t])),parent=new Group(),pickables=[];
 createTerrainBatch({tiles,map,factory:stoneTile,parent,pickables});parent.updateMatrixWorld(true);
 for(const t of tiles){const ray=new Raycaster(new Vector3(t.x-6,8,t.z-6),new Vector3(0,-1,0)),hit=ray.intersectObjects(pickables)[0];assert.equal(terrainHitData(hit).tile,t);assert.equal(hit.point.y,t.h);}
});

test('Cinderhold has a continuous tall perimeter including every corner',()=>{
 const tiles=makeCinderholdTiles(),world=new Map(tiles.map(t=>[`${t.x},${t.z}`,t]));
 for(let z=1;z<=32;z++)for(let x=1;x<=40;x++)if(x===1||x===40||z===1||z===32){
  const wall=world.get(`${x},${z}`);assert.ok(wall?.blocked&&wall.blocksSight,`sealed boundary ${x},${z}`);
 }
 for(const wall of tiles.filter(t=>t.blocksSight))for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){
  const floor=world.get(`${wall.x+dx},${wall.z+dz}`);if(floor&&!floor.blocked)assert.ok(wall.h-floor.h>=2.5,`wall height at ${wall.x},${wall.z}`);
 }
});
