import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {MODEL_CATALOG} from './model-catalog.js';
import {MAIN_HANDS,OFF_HANDS,ATTACK_MOTIONS,BLOCK_MOTIONS} from './preview-loadout.js';
import './model-preview.css';

export function createModelPreview(){
 const modal=document.createElement('dialog');modal.id='dev-model-preview';modal.setAttribute('aria-labelledby','model-preview-title');
 modal.innerHTML=`<div class="preview-header"><div><small>DEVELOPMENT</small><h2 id="model-preview-title">Model viewer</h2></div><div class="preview-header-actions"><button data-reset-view>Reset view</button><button data-close aria-label="Close model viewer">Close</button></div></div>
 <div class="preview-controls"><label>Model<select data-model></select></label><label>Animation<select data-motion></select></label><label>Expression<select data-expression></select></label><label data-prop-label hidden>Held item<select data-prop><option>Generic item</option><option>Raw Pondfish</option><option>Top Hat</option></select></label><label data-attack-label hidden>Attack motion<select data-attack-motion></select></label><label data-block-label hidden>Block motion<select data-block-motion></select></label><div class="preview-playback"><button data-play>Pause</button><button data-restart>Restart</button></div><div class="preview-loadout" data-loadout hidden><label>Main hand<select data-main-hand></select></label><label>Off hand<select data-off-hand></select></label><label>Combat style<select data-combat-style><option value="weapon">Weapon</option><option value="magic">Magic</option></select></label><button data-reset-loadout>Reset loadout</button><p data-loadout-note>Equipment stays visible during casting. Skilling tools temporarily replace it.</p></div></div>
 <div class="preview-stage"><canvas aria-label="Model preview: drag to rotate, scroll or pinch to zoom"></canvas></div><p class="preview-hint">Drag to rotate · scroll or pinch to zoom. Uses the same models as the game.</p>`;
 document.body.append(modal);
 const canvas=modal.querySelector('canvas'),stage=modal.querySelector('.preview-stage'),select=modal.querySelector('[data-model]'),motion=modal.querySelector('[data-motion]'),expression=modal.querySelector('[data-expression]'),play=modal.querySelector('[data-play]');
 const prop=modal.querySelector('[data-prop]'),propLabel=modal.querySelector('[data-prop-label]');
 const mainHand=modal.querySelector('[data-main-hand]'),offHand=modal.querySelector('[data-off-hand]'),style=modal.querySelector('[data-combat-style]'),attackMotion=modal.querySelector('[data-attack-motion]'),blockMotion=modal.querySelector('[data-block-motion]');
 for(const [select,options] of [[mainHand,MAIN_HANDS],[offHand,OFF_HANDS],[attackMotion,ATTACK_MOTIONS],[blockMotion,BLOCK_MOTIONS]])select.replaceChildren(...options.map(([id,label])=>new Option(label,id)));
 const settings=()=>({mainHand:mainHand.value,offHand:offHand.value,style:style.value,attackMotion:attackMotion.value,blockMotion:blockMotion.value});
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;
 const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight('#fffce8','#879981',2.6));const sun=new THREE.DirectionalLight('#fff3d3',3);sun.position.set(-8,19,5);scene.add(sun);
 const camera=new THREE.PerspectiveCamera(35,1,.01,100),controls=new OrbitControls(camera,canvas);controls.enablePan=false;controls.rotateSpeed=.7;controls.minPolarAngle=.05;controls.maxPolarAngle=Math.PI-.05;
 controls.addEventListener('start',()=>canvas.style.cursor='grabbing');controls.addEventListener('end',()=>canvas.style.cursor='grab');
 for(const entry of [...MODEL_CATALOG].sort((a,b)=>a.name.localeCompare(b.name)))select.add(new Option(entry.name,entry.name));
 select.value='Slime';
 let instance,age=0,last=0,frame=0,paused=false,center=new THREE.Vector3(),radius=1,disposed=false;
 function disposeModel(){if(!instance)return;scene.remove(instance.group);const geometries=new Set(),materials=new Set();instance.group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[])materials.add(m);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());instance=null;}
 function fit(reset=false){const direction=reset?new THREE.Vector3(.45,.3,1).normalize():camera.position.clone().sub(controls.target).normalize();const half=Math.atan(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*Math.min(1,camera.aspect)),distance=radius/Math.sin(half)*1.15;controls.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance);controls.minDistance=radius*.8;controls.maxDistance=radius*12;camera.near=Math.max(.001,radius/100);camera.far=radius*40;camera.updateProjectionMatrix();controls.update();}
 function resize(){if(!modal.open)return;const {width,height}=stage.getBoundingClientRect();if(!width||!height)return;renderer.setSize(width,height,false);camera.aspect=width/height;fit();}
 function measure(){const bounds=new THREE.Box3().makeEmpty();const include=()=>{instance.group.updateMatrixWorld(true);instance.group.traverseVisible(o=>{if(!o.geometry)return;o.geometry.computeBoundingBox();bounds.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));});};include();if(motion.value==='Celebration'){instance.update?.(1.2,motion.value,0,expression.value,prop.value,settings());include();instance.update?.(age,motion.value,0,expression.value,prop.value,settings());}if(select.value==='Corgi'&&['Petting','Sleeping'].includes(motion.value)){for(const t of (motion.value==='Sleeping'?[2,3,4,5.8]:[.5,1.2,1.85,2.3])){instance.update?.(t,motion.value,0,expression.value,prop.value,settings());include();}instance.update?.(age,motion.value,0,expression.value,prop.value,settings());}const sphere=bounds.getBoundingSphere(new THREE.Sphere());center.copy(sphere.center);radius=Math.max(.2,sphere.radius);}
 function load(){disposeModel();const entry=MODEL_CATALOG.find(e=>e.name===select.value);const defaultMotion=entry.motions.includes('Idle')?'Idle':entry.motions.includes('Static')?'Static':entry.motions[0];motion.replaceChildren(...[defaultMotion,...entry.motions.filter(m=>m!==defaultMotion).sort((a,b)=>a.localeCompare(b))].map(m=>new Option(m,m)));motion.value=defaultMotion;motion.disabled=entry.motions.length===1;expression.replaceChildren(new Option(entry.expressions?'Default':'Not applicable','default'),...[...(entry.expressions||[])].sort((a,b)=>a.localeCompare(b)).map(e=>new Option(e,e)));expression.disabled=!entry.expressions;instance=entry.create(renderer);instance.update?.(0,motion.value,0,expression.value,prop.value,settings());scene.add(instance.group);measure();age=0;paused=false;updatePlayback();fit(true);}
 function updatePlayback(){const slime=!!MODEL_CATALOG.find(e=>e.name===select.value)?.loadout;modal.querySelector('[data-loadout]').hidden=!slime;modal.querySelector('[data-attack-label]').hidden=!slime||motion.value!=='Attack';modal.querySelector('[data-block-label]').hidden=!slime||motion.value!=='Block';propLabel.hidden=motion.value!=='Celebration';const animated=!!instance?.update&&!['Static','Closed','Open','Broken','Repaired'].includes(motion.value);play.disabled=!animated;play.textContent=paused?'Play':'Pause';play.setAttribute('aria-pressed',String(paused));}
 function draw(now){if(!modal.open||disposed)return;const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!paused){age+=dt;instance?.update?.(age,motion.value,dt,expression.value,prop.value,settings());}controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(draw);}
 const observer=new ResizeObserver(resize);observer.observe(stage);
 function changeLoadout(){const bow=mainHand.value==='bows';if(bow)offHand.value='';offHand.disabled=bow;modal.querySelector('[data-loadout-note]').textContent=bow?'Bow uses both hands. Casting keeps equipment visible; skilling tools temporarily replace it.':'Casting keeps equipment visible; skilling tools temporarily replace it.';instance?.update?.(age,motion.value,0,expression.value,prop.value,settings());measure();fit();}
 for(const control of [mainHand,offHand,style,attackMotion,blockMotion])control.onchange=changeLoadout;
 modal.querySelector('[data-reset-loadout]').onclick=()=>{mainHand.value=offHand.value=attackMotion.value=blockMotion.value='';style.value='weapon';changeLoadout();};
 prop.onchange=()=>{instance?.update?.(age,motion.value,0,expression.value,prop.value,settings());measure();fit();};
 select.onchange=load;expression.onchange=()=>{instance?.update?.(age,motion.value,0,expression.value,prop.value,settings());};motion.onchange=()=>{age=0;instance.update?.(0,motion.value,0,expression.value,prop.value,settings());measure();fit();updatePlayback();};play.onclick=()=>{paused=!paused;updatePlayback();};modal.querySelector('[data-restart]').onclick=()=>{age=0;instance?.update?.(0,motion.value,0,expression.value,prop.value,settings());};modal.querySelector('[data-reset-view]').onclick=()=>fit(true);modal.querySelector('[data-close]').onclick=()=>modal.close();modal.addEventListener('close',()=>{cancelAnimationFrame(frame);last=0;disposeModel();});
 return {show(){if(modal.open)return;modal.showModal();load();resize();last=0;frame=requestAnimationFrame(draw);},dispose(){disposed=true;modal.close();observer.disconnect();controls.dispose();renderer.dispose();modal.remove();}};
}
